source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

#-SOAP Server
gem 'wash_out'
#-SOAP Client
gem 'savon'
#-jQuery
gem 'jquery-rails'

# gem 'unicorn'

group :test do
  gem 'turn', '~> 0.8.3', :require => false
end
